-- 회원 및 권한 테이블
CREATE TABLE AUTHORITY
( 
	AUTH VARCHAR2(20) PRIMARY KEY
);
DROP TABLE AUTHORITY;
SELECT * FROM AUTHORITY;


CREATE TABLE MEMBER
(
   ID                    VARCHAR2(20)  PRIMARY KEY,
   PASSWORD              VARCHAR2(20)  NOT NULL ,
   NAME                  VARCHAR2(20)  NOT NULL ,
   PHONE                 VARCHAR2(20)  NOT NULL ,
   PAYPASSWORD           VARCHAR2(20)  NOT NULL ,
   BALANCE               NUMBER,
   REGDATE               DATE  NOT NULL,
   AUTH                  VARCHAR2(20)  NOT NULL ,
   CONSTRAINT MEMBER_AUTH FOREIGN KEY(AUTH) REFERENCES AUTHORITY(AUTH)
);
SELECT * FROM MEMBER;
DROP TABLE MEMBER;


--가맹점 부분 ( 업종분류 , 가맹점, 가맹점별 업종)
-- 업종분류
CREATE TABLE CATEGORY
(
   CATE_NAME VARCHAR2(20)  PRIMARY KEY
);
DROP TABLE CATEGORY;

-- 가맹점 
CREATE SEQUENCE S_NO_SEQ 
START WITH 100
NOCACHE;
DROP SEQUENCE S_NO_SEQ;
--SELECT S_NO_SEQ.NEXTVAL FROM DUAL;
--DROP SEQUENCE S_NO_SEQ;

CREATE TABLE STORE
(
   S_NO                  NUMBER  PRIMARY KEY,
   S_NAME                VARCHAR2(40)  NOT NULL ,
   S_ADDRESS             VARCHAR2(100)  NOT NULL ,
   TEL                   VARCHAR2(20)  NOT NULL ,
   OPENDAY               VARCHAR2(30)  NOT NULL ,
   S_IMG               	VARCHAR2(500)  NOT NULL ,
   ID                    VARCHAR2(20)  NOT NULL ,
   CONSTRAINT STORE_ID FOREIGN KEY(ID) REFERENCES MEMBER(ID)
);
SELECT * FROM STORE;
DROP TABLE STORE;

-- 가맹점별 업종
CREATE TABLE STORE_CATEGORY
(
   CATE_NAME             VARCHAR2(20)  NOT NULL ,
   S_NO                  NUMBER  NOT NULL,
   CONSTRAINT PK_STORE_CATEGORY PRIMARY KEY(CATE_NAME, S_NO),
   CONSTRAINT SC_CATE_NAME FOREIGN KEY(CATE_NAME) REFERENCES CATEGORY(CATE_NAME),
   CONSTRAINT SC_S_NO FOREIGN KEY(S_NO) REFERENCES STORE(S_NO)
);
DROP TABLE STORE_CATEGORY;
SELECT * FROM STORE_CATEGORY;
   
-- 메뉴
CREATE SEQUENCE M_NO_SEQ
START WITH 2000
NOCACHE;
DROP SEQUENCE M_NO_SEQ;

-- 수정: m_price를 기본가격으로 수정 
CREATE TABLE MENU
(
   M_NO                  NUMBER  PRIMARY KEY,
   M_NAME                VARCHAR2(40)  NOT NULL ,
   M_INFO                CLOB NULL,
   M_IMG               	VARCHAR2(500)  NOT NULL ,
   S_NO                  NUMBER  NOT NULL ,
   CONSTRAINT MENU_S_NO FOREIGN KEY(S_NO) REFERENCES STORE(S_NO)
);
DROP TABLE MENU;

-- 옵션들 (SIZE, HOT/ICE)
-- 사이즈
CREATE TABLE SIZE_TYPE
(
   SIZE_TYPE VARCHAR2(20) PRIMARY KEY 
);

-- hot/ice
CREATE TABLE HOT_ICE_TYPE
(
   HOT_ICE VARCHAR2(20) PRIMARY KEY
);

-- 메뉴상세정보 
-- 수정: md_add_price 옵션 추가금액으로 변경 
CREATE SEQUENCE MD_NO_SEQ
START WITH 10101
NOCACHE;
DROP SEQUENCE MD_NO_SEQ;

CREATE TABLE MENU_DETAIL
(
   MD_NO                 NUMBER  PRIMARY KEY,
   MD_PRICE         NUMBER  NOT NULL ,
   HOT_ICE               VARCHAR2(20)  NULL ,
   SIZE_TYPE             VARCHAR2(20)  NULL ,
   M_NO                  NUMBER  NOT NULL ,
   CONSTRAINT MD_M_NO FOREIGN KEY(M_NO) REFERENCES MENU(M_NO),
   CONSTRAINT MD_HOT_ICE FOREIGN KEY(HOT_ICE) REFERENCES HOT_ICE_TYPE(HOT_ICE),
   CONSTRAINT MD_SIZE_TYPE FOREIGN KEY(SIZE_TYPE) REFERENCES SIZE_TYPE(SIZE_TYPE)
);
DROP TABLE MENU_DETAIL;

-- 주문처리상태
CREATE TABLE ORDER_STATUS
(
   O_STATUS VARCHAR2(20) PRIMARY KEY
);

-- 주문
CREATE SEQUENCE O_NO_SEQ 
START WITH 1000
NOCACHE;
DROP SEQUENCE O_NO_SEQ;

CREATE TABLE ORDERS
(
   O_NO                  NUMBER  PRIMARY KEY,
   QUANTITY              NUMBER  NOT NULL ,
   O_PRICE               NUMBER  NOT NULL ,
   O_DATE                DATE  NOT NULL ,
   MD_NO                 NUMBER  NOT NULL ,
   ID                    VARCHAR2(20)  NOT NULL ,
   O_STATUS              VARCHAR2(20)  NOT NULL ,
   CONSTRAINT ORDERS_MD_NO1  FOREIGN KEY(MD_NO) REFERENCES MENU_DETAIL(MD_NO),
   CONSTRAINT ORDERS_ID1  FOREIGN KEY(ID) REFERENCES MEMBER(ID),
   CONSTRAINT ORDERS_O_STATUS1  FOREIGN KEY(O_STATUS) REFERENCES ORDER_STATUS(O_STATUS)
);
SELECT * FROM ORDERS;
DROP TABLE ORDERS;

